apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: ssgenerals-backend
  name: ssgenerals-backend
  namespace: default
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 8080 #CHANGE
    protocol: TCP
    targetPort: 8080 #CHANGE
  selector:
    app: ssgenerals-backend
  sessionAffinity: None #CHANGE
  # type: LoadBalancer
  type: ClusterIP  # 👈 Internal-only access