apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssgenerals-backend
  name: ssgenerals-backend
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: ssgenerals-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssgenerals-backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql.default.svc.cluster.local 3306; do echo "Waiting for MySQL"; sleep 2; done']
      containers:
      - name: ssgenerals-backend
        image: jimsonrats/ssgenerals-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql.default.svc.cluster.local:3306/ssgenerals?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: validate
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info"
        - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
          value: "30000"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
          value: "5"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        startupProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 45
          periodSeconds: 10
      terminationGracePeriodSeconds: 60
