apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssgenerals-backend
  name: ssgenerals-backend
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: ssgenerals-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssgenerals-backend
    spec:
      containers:
      - name: ssgenerals-backend
        image: jimsonrats/ssgenerals-backend
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/ssgenerals
          - name: SPRING_DATASOURCE_USERNAME
            value: root
          - name: SPRING_DATASOURCE_PASSWORD
            value: "1234"
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30