name: CI/CD Pipeline

on:
 push:
  branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # BACKEND: Build and Push Docker Image

      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: |
          cd backend/SuryaSankaraBackend
          mvn clean package -DskipTests

      - name: Build Backend Docker Image
        run: |
          
          docker build -t jimsonrats/ssgenerals-backend:latest -f Dockerfile.backend .

      #FRONTEND: Build Angular & Push Docker Image
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular Dependencies & Build
        run: |
          cd frontend
          npm install
          npm run build --prod

      - name: Build Frontend Docker Image
        run: |
          docker build -t jimsonrats/ssgenerals-frontend:latest -f Dockerfile.frontend .

      #Push Docker Images to Docker Hub
      - name: Login to Docker Hub 
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin


      - name: Push Backend Image
        run: docker push jimsonrats/ssgenerals-backend:latest

      - name: Push Frontend Image
        run: docker push jimsonrats/ssgenerals-frontend:latest

      
        # - name: Start SSH agent and Add key
        # run: |

      - name: Set up SSh key

        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)" # Start SSH agent
          ssh-add~/.ssh/id_rsa # Add key with passphrase
          ssh-add -1 # Debug List loaded keys

      - name: Add Server SSH Key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

          chmod 644 ~/.ssh/known_hosts

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      # Deploy the containers
      - name: Deploy to EC@ Server
        run: |

          ssh -vvv -o StrictHostKeyChecking=no ${{secrets.SSH_USERNAME}}@${{secrets.EC2_PUBLIC_IP}} <<'EOF'
            echo "SSH works!" 
            sudo su

            # Navigate to deployment directory
            cd /home/ubuntu

            # Download the docker compose from repo

            mkdir ss
            curl -o ss/docker-compose.yml https://github.com/JimsonR/SSGeneralStoreDeployment/blob/0d2dc70eecfa6779d1f80b753c8eaac98405b197/docker-compose.yml

            docker pull jimsonrats/ssgenerals-backend:latest 
            docker pull jimsonrats/ssgenerals-frontend:latest
            # cd ..
            ss/docker-compose down
            ss/docker-compose up -d --force-recreate
          EOF




